### ISSUE TITLE
Running script get CREATE_FAILED setting up AWS::Lambda::Function 

### ISSUE THREAD

**Issue by andrewliles** [awslabs/ebs-snapshot-scheduler#5]
Using the instructions on http://docs.aws.amazon.com/solutions/latest/ebs-snapshot-scheduler/deployment.html#step1 and keeping almost exactly the defaults, however setting region to be `eu-west-2` (London), the formation failed with the error:

```
Your access has been denied by S3, please make sure your request credentials have permission to GetObject for solutions-eu-west-2/library/solution-helper/v3/solution-helper.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied
```

Could it be that this solution is not deployed to or available in that region yet?

**Comment by gsinghlab** [comment]
thank you for raising this issue, 
we are investigating it and update you once we resolve it

**Comment by groverlalit** [comment]
The issue has been resolved. Please try launching the solution using the same link again.
Thanks for your valuable feedback.

**Comment by andrewliles** [comment]
Confirmed fixed.  Thank you @groverlalit
